version: "3"

services:

    caddy:
        image: caddy:2-alpine
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./public:/var/www/html/public
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - app

    app:
        build: 
            context: .
            dockerfile: Dockerfile.prod
        # image: tgsearch
        restart: unless-stopped
        volumes:
            - '.:/var/www/html'
        depends_on:
            - pgsql
            - redis
            - meilisearch

    pgsql:
        image: 'postgres:17-alpine'
        restart: unless-stopped
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dbdata:/var/lib/postgresql/data'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        volumes:
            - 'meilisearch:/meili_data'
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://localhost:7700/health'
            retries: 3
            timeout: 5s

volumes:
    caddy_data:
    caddy_config:
    dbdata:
        driver: local
    redis:
        driver: local
    meilisearch:
        driver: local
