name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            
            directory_path="/app/TGSearch"
            
            echo "检查并安装 Git"
            if ! command -v git &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y git
            fi

            echo "检查并安装 Docker"
            if ! command -v docker &>/dev/null; then
              echo "Installing Docker..."
              sudo DEBIAN_FRONTEND=noninteractive apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
            fi
            
            echo "检查并安装 Docker Compose"
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
              # 创建软链接以保持兼容性
              sudo ln -sf /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
            fi
            
            echo "创建目录 $directory_path（如果不存在）"
            mkdir -p $directory_path
            
            cd $directory_path 
            
            if [ -z "$(ls -A $directory_path)" ]; then
              echo "目录为空，Clone git"
              git clone https://github.com/${{ github.repository }}.git .
            else
              echo "目录不为空 Pull git"
              git config --global --add safe.directory $(pwd)
              git reset --hard origin/main && git pull origin main
            fi
                        
            docker-compose -f docker-compose-prod.yml down --remove-orphans
            docker-compose -f docker-compose-prod.yml up -d --build --remove-orphans